"""Pydantic schemas for the growth plan agent pipeline."""

from pydantic import BaseModel


class CrawlStrategy(BaseModel):
    """Per-link crawl directive generated by the Pre-Crawl Strategist."""

    url: str
    link_type: str          # "github" | "linkedin" | "drive" | "notion" | "other"
    depth: str              # "surface" | "medium" | "deep"
    focus_areas: list[str]  # personalized directives for the crawl agent
    why: str                # rationale tied to this user's CV + career goal


class CrawlResult(BaseModel):
    """Extracted signals from one crawled URL."""

    url: str
    link_type: str
    signals: list[str]   # extracted facts and observations
    raw_summary: str     # full extracted text summary


class SkillStep(BaseModel):
    """One learning step within a roadmap path."""

    skill: str
    why: str
    resource: str
    resource_type: str   # "course" | "book" | "project" | "community"


class RoadmapPath(BaseModel):
    """One of three possible growth paths for the user."""

    title: str
    rationale: str           # why this path fits THIS specific user
    timeline_estimate: str   # e.g. "4-6 months"
    target_role: str
    unfair_advantage: str    # what makes this user uniquely suited
    skill_steps: list[SkillStep]


class GapQuestion(BaseModel):
    """A follow-up question card for the frontend to render."""

    id: str                      # stable key for answer mapping
    question: str
    context: str                 # why the agent is asking this
    path_relevance: list[str]    # which paths this question helps unlock


class RoadmapAnalysisResult(BaseModel):
    """Full output of one analysis agent invocation."""

    stage: str                          # "preliminary" | "final"
    confidence_scores: dict[str, int]   # {fill_gap: 0-100, multidisciplinary: 0-100, pivot: 0-100}
    gap_questions: list[GapQuestion]    # empty list on final stage
    path_fill_gap: RoadmapPath
    path_multidisciplinary: RoadmapPath
    path_pivot: RoadmapPath
    diff_summary: str                   # empty string on preliminary stage


class StrategistOutput(BaseModel):
    """Batch output from the Pre-Crawl Strategist Agent."""

    strategies: list[CrawlStrategy]
