import type { Language, AppView, ActionItem, ProcessingStep, FlowMeta, Artifact } from "./common";
import type { ProfileData } from "./profile";
import type { CVAnalysisResult } from "./cv";
import type { ServicePoint, ServiceCategory, GuideMessage } from "./services";
import type { ChatMessage } from "./chat";
import type { JobListing, JobMatch, TrendingSkill, UpskillingSummary, TransitRoute, CommuteEstimate } from "./jobs";
import type { CitizenMeta } from "./profile";
import type { NewsArticle, NewsCategory, NewsComment, ReactionType } from "./news";
import type { MapCommand } from "./map";
import type { HousingListing } from "./housing";
import type { PersonalizedRoadmap } from "./roadmap";
import type { GrowthStage, GrowthAnalysis, GrowthProgressData, RoadmapPath, PathKey } from "./growth";

export interface AppState {
  messages: ChatMessage[];
  language: Language;
  activeView: AppView;
  activeFlow: FlowMeta | null;
  profile: ProfileData;
  artifacts: Artifact[];
  activeArtifactId: string | null;
  actionItems: ActionItem[];
  isTyping: boolean;
  processingSteps: ProcessingStep[];
  cvResult: CVAnalysisResult | null;
  cvFileName: string | null;
  cvAnalyzing: boolean;
  cvJobId: string | null;
  cvUploadId: string | null;
  cvProgress: number;
  cvStage: string;
  selectedPin: ServicePoint | null;
  activeCategories: ServiceCategory[];
  servicePoints: ServicePoint[];
  guideMessages: GuideMessage[];
  guideInitialized: boolean;
  guideTyping: boolean;
  jobListings: JobListing[];
  jobMatches: JobMatch[];
  trendingSkills: TrendingSkill[];
  jobsLoading: boolean;
  upskillingSummary: UpskillingSummary | null;
  transitRoutes: TransitRoute[];
  commuteEstimates: CommuteEstimate[];
  citizenMeta: CitizenMeta | null;
  newsArticles: NewsArticle[];
  newsLoading: boolean;
  newsCategory: NewsCategory;
  newsComments: NewsComment[];
  likedArticleIds: string[];
  selectedArticleId: string | null;
  newsMapVisible: boolean;
  newsMapMode: "pins" | "heat";
  newsReactions: Record<string, Record<ReactionType, number>>;
  userReactions: Record<string, ReactionType>;
  articleReactions: Record<string, string>;
  flaggedArticleIds: string[];
  chatBubbleOpen: boolean;
  chatBubbleHasUnread: boolean;
  mapCommand: MapCommand | null;
  guidePendingMessage: string | null;
  housingListings: HousingListing[];
  activeRoadmap: PersonalizedRoadmap | null;
  roadmapCompletedStepIds: string[];
  growthStage: GrowthStage;
  growthAnalysis: GrowthAnalysis | null;
  growthIntakeId: string | null;
  growthProgress: GrowthProgressData | null;
  growthDiffVisible: boolean;
  activeRoadmapPath: RoadmapPath | null;
  activeRoadmapAnalysisId: string | null;
  activeRoadmapPathKey: PathKey | null;
}
